### ISSUE TITLE
Cidades por ordem alfabeticas

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS-Suporte#12]
No ADD e no  filtro cidades deixar or ordem alfabéticas. 
![captura de tela de 2015-09-17 13 24 36](https://cloud.githubusercontent.com/assets/14019630/9939198/71a59be2-5d3f-11e5-89d3-6cd4e144d478.png)

**Comment by mateusaires3** [comment]
Categoria adicionado, em seguida colocarei em ordem alfabetica
