### ISSUE TITLE
Painel de Avisos

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS-Suporte#21]
Adicionar Hora 
Adicionar Cidade
Catgorias:
Ping Alto
Servidor Travado
Interferência
Enlace
Sem acesso
Lentidão
Sistema de TV
Rota parada
LEVEL3
Rompimento de Fibra
Quedas 
Manutenção
Sistema Fibra
Sistema Radio

**Comment by pcalves12** [comment]
Falta de Energia

**Comment by mateusaires3** [comment]
Adicionado todos os itens ao sistema
