### ISSUE TITLE
Protocolos Aguardando Finalização

### ISSUE THREAD

**Issue by josycosta** [mateusaires3/SAS-Suporte#31]
Lista de Chamados aguardando Finalização do Colaborador				
Nome do Colaborador	/ Protocolo 	/ Data da conclusão do Técnico /	Data da Finalização 	Status 

https://docs.google.com/spreadsheets/d/1DKRESa3dkQazibItuOBTOJmpkySB275C9WnNJEeCOwg/edit#gid=0

**Comment by mateusaires3** [comment]
resolvido
